config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :project_roles, :project_milestones, :professions, :project_attachments, :states,
            :states, :states, :activity_members, :organizations, :activities, :project_members,
            :project_donors, :project_partners, :projects, :members, :roles, :donors, :branches,
            :locations, :states, :users, :tags, :costs, :lines

  resource :trello_webhooks, only: %i(show create), defaults: { formats: :json }

  resources :projects do
    resources :project_attachments
  end

  # resources :projects do
  #   resources :project_members
  # end
  
  resources :activities do
    resource :cost
  end

  resource :project do
    post :add_member
    #get :remove_member
  end

  resource :activity do
    post :add_member
    #get :remove_member
  end
  
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1 , default: :true) do
      resources :projects
      resources :activities
    end
  end

  #get '/auth/twitter/callback', to: 'sessions#create'
  
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
    match "/confirm", to: "confirmations#confirm", via: :put 
    get '/auth/failure', to: 'sessions#new'
  end

  devise_for :users, :path => '', :path_names => { sign_in: 'login', sign_out: 'logout'}, :controllers => { omniauth_callbacks: "callbacks", confirmations: "confirmations", sessions: "sessions", registrations: "registrations" }

  get 'settings' => 'dashboard#settings', :as => "settings"

  root :to => "projects#index"
end

app/models/activity_member.rb
class ActivityMember < ActiveRecord::Base
  belongs_to :member 
  belongs_to :activity
  belongs_to :role
end

app/controllers/activity_members_controller.rb
class ActivityMembersController < ApplicationController
  load_and_authorize_resource
  before_action :set_activity_member, only: [:show, :edit, :update, :destroy]

  # GET /activity_members
  # GET /activity_members.json
  def index
    @activity_members = ActivityMember.all
  end

  # GET /activity_members/1
  # GET /activity_members/1.json
  def show
  end

  # GET /activity_members/new
  def new
    @activity_member = ActivityMember.new
  end

  # GET /activity_members/1/edit
  def edit
  end

  # POST /activity_members
  # POST /activity_members.json
  def create
    @activity_member = ActivityMember.new(activity_member_params)

    respond_to do |format|
      if @activity_member.save
        format.html { redirect_to @activity_member, notice: 'Activity member was successfully created.' }
        format.json { render :show, status: :created, location: @activity_member }
      else
        format.html { render :new }
        format.json { render json: @activity_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_members/1
  # PATCH/PUT /activity_members/1.json
  def update
    respond_to do |format|
      if @activity_member.update(activity_member_params)
        format.html { redirect_to @activity_member, notice: 'Activity member was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_member }
      else
        format.html { render :edit }
        format.json { render json: @activity_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_members/1
  # DELETE /activity_members/1.json
  def destroy
    @activity = @activity_member.activity
    @activity_member.destroy
    respond_to do |format|
      format.html { redirect_to @activity, notice: 'Activity member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_member
      @activity_member = ActivityMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_member_params
      params.require(:activity_member).permit(:activity_id, :member_id, :created_by, :updated_by)
    end
end

app/helpers/activity_members_helper.rb
module ActivityMembersHelper
end

app/views/activity_members/_form.html.erb
<%= form_for @activity_member, :html => {:class => 'form-horizontal'} do |f| %>
  <% if @activity_member.errors.any? %>
    <% @activity_member.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  

      <div class="form-group">
        <%= f.label :activity_id, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group">
            <%= f.select :activity_id, Activity.all.collect {|p| [ p.name, p.id ] }, {}, { :class => 'form-control' } %>
            <span class="input-group-btn">
            <%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_activity_path, :class => 'btn btn-default', :target => '_blank' %>
            <%= link_to raw('<span class="glyphicon glyphicon-play"></span>'), activities_path, :class => 'btn btn-default goto' %>
            </span>
          </div>
        </div>
      </div>


      <div class="form-group">
        <%= f.label :member_id, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group">
            <%= f.select :member_id, Member.all.collect {|p| [ p.name, p.id ] }, {}, { :class => 'form-control' } %>
            <span class="input-group-btn">
            <%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_member_path, :class => 'btn btn-default', :target => '_blank' %>
            <%= link_to raw('<span class="glyphicon glyphicon-play"></span>'), members_path, :class => 'btn btn-default goto' %>
            </span>
          </div>
        </div>
      </div>

  
  <div class="form-group">
    <label class="col-sm-2 control-label" for="attachment_file"></label>
    <div class="col-sm-10"><button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-floppy-disk"></span> <%= t('views.epp.links.save') %></button></div>
  </div>
      
<% end %>

app/views/activity_members/edit.html.erb
<%- title t("views.epp.links.edit %{model}", :model => t("views.activity_members.activity_members")) %>

<div class="col-lg-12">
	<div class="page-header">
		<h1><%= t("views.epp.links.edit %{model}", :model => t("views.activity_members.activity_members")) %></h1>
	</div>
	<%= render 'form' %>

</div>

app/views/activity_members/index.html.erb
<%- title t "views.application_layout.activity_members" %>
<div class="col-xs-12">

  <div class="page-header">
    <h1><%= t "views.application_layout.activity_members" %> <small><%= t("views.epp.Listing of all %{model}", :model => t("views.activity_members.activity_members")) %></small></h1>
  </div>


  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
              <th><%= t("views.activity_members.activity_id") %></th>
              <th><%= t("views.activity_members.member_id") %></th>
              <th class="hidden-print"></th>
        </tr>
      </thead>

      <tbody>
        <% @activity_members.each do |activity_member| %>
          <tr>
    
            <td><%= link_to activity_member.activity.name, activity_member.activity if activity_member.activity_id %></td>

            <td><%= link_to activity_member.member.name, activity_member.member if activity_member.member_id %></td>
            <td class="hidden-print actions">
              <div class="btn-group">
                <%= link_to t('views.epp.links.show'), activity_member , :class => 'btn btn-xs btn-default' %>
                <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                  <span class="caret"></span>
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to t('views.epp.links.edit'), edit_activity_member_path(activity_member) %></li>
                  <li><%= link_to t('views.epp.links.destroy'), activity_member, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to t('views.epp.links.new %{model}', :model => t("views.activity_members.activity_member")), new_activity_member_path, :class => 'btn btn-primary btn-lg hidden-print' %>
</div>

app/views/activity_members/new.html.erb
<%- title t("views.epp.links.new %{model}", :model => t("views.activity_members.activity_members")) %>
<div class="col-lg-12">
	<div class="page-header">
		<h1><%= t("views.epp.links.new %{model}", :model => t("views.activity_members.activity_members")) %></h1>
	</div>
	<%= render 'form' %>

</div>

app/views/activity_members/show.html.erb
<%- title "#{@activity_member.activity_id}" %>
<div class="col-lg-12 show">
	<div class="page-header">
		<h1><%= @activity_member.activity_id %></h1>
	</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.activity_members.activity_id") %></strong></div>

		<div class="col-sm-10"><%= link_to @activity_member.activity.name, @activity_member.activity if @activity_member.activity_id %></div>
		</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.activity_members.member_id") %></strong></div>

		<div class="col-sm-10"><%= link_to @activity_member.member.name, @activity_member.member if @activity_member.member_id %></div>
		</div>


	<div class="buttons">
		<%= link_to t('views.epp.links.edit'), edit_activity_member_path(@activity_member), :class => 'btn btn-warning' %>
		<%= link_to t('views.epp.links.back'), activity_members_path, :class => 'btn btn-default' %>
	</div>
</div>