config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :project_roles, :project_milestones, :professions, :project_attachments, :states,
            :states, :states, :activity_members, :organizations, :activities, :project_members,
            :project_donors, :project_partners, :projects, :members, :roles, :donors, :branches,
            :locations, :states, :users, :tags, :costs, :lines

  resource :trello_webhooks, only: %i(show create), defaults: { formats: :json }

  resources :projects do
    resources :project_attachments
  end

  # resources :projects do
  #   resources :project_members
  # end
  
  resources :activities do
    resource :cost
  end

  resource :project do
    post :add_member
    #get :remove_member
  end

  resource :activity do
    post :add_member
    #get :remove_member
  end
  
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1 , default: :true) do
      resources :projects
      resources :activities
    end
  end

  #get '/auth/twitter/callback', to: 'sessions#create'
  
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
    match "/confirm", to: "confirmations#confirm", via: :put 
    get '/auth/failure', to: 'sessions#new'
  end

  devise_for :users, :path => '', :path_names => { sign_in: 'login', sign_out: 'logout'}, :controllers => { omniauth_callbacks: "callbacks", confirmations: "confirmations", sessions: "sessions", registrations: "registrations" }

  get 'settings' => 'dashboard#settings', :as => "settings"

  root :to => "projects#index"
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  has_many :lines
  belongs_to :activity

  accepts_nested_attributes_for :lines, allow_destroy: true
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new(activity_id: params[:activity_id])
    @cost.lines.build
  end
  
  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to activity_cost_url(@cost.activity), notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to activity_cost_url(@cost.activity), notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to @cost.activity, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @activity  = Activity.find(params[:activity_id])
      @cost = @activity.cost
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:activity_id, :total_cost, :created_by, :updated_by, lines_attributes: [:id, :quantity, :price, :name, :_destroy])
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for [@activity, @cost], url: activity_cost_url, :html => {:class => 'form-horizontal'} do |f| %> 
  <% if @cost.errors.any? %>
    <% @cost.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>


  <%= f.hidden_field :activity_id, value: @cost.activity_id%>

  <%= render :partial => "lines/form", :locals => {f: f} %>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="attachment_file"></label>
    <div class="col-sm-10"><button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-floppy-disk"></span> <%= t('views.epp.links.save') %></button></div>
  </div>
      
<% end %>

app/views/costs/edit.html.erb
<%- title t("views.epp.links.edit %{model}", :model => t("views.costs.costs")) %>

<div class="col-lg-12">
	<div class="page-header">
		<h1><%= t("views.epp.links.edit %{model}", :model => t("views.costs.costs")) %></h1>
	</div>
	<%= render 'form' %>

</div>

app/views/costs/index.html.erb
<%- title t "views.application_layout.costs" %>
<div class="col-xs-12">

  <div class="page-header">
    <h1><%= t "views.application_layout.costs" %> <small><%= t("views.epp.Listing of all %{model}", :model => t("views.costs.costs")) %></small></h1>
  </div>


  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
              <th><%= t("views.costs.total_cost") %></th>
              <th class="hidden-print"></th>
        </tr>
      </thead>

      <tbody>
        <% @costs.each do |cost| %>
          <tr>
    

            <td><%= cost.total_cost %></td>
                <td class="hidden-print actions">
              <div class="btn-group">
                <%= link_to t('views.epp.links.show'), cost , :class => 'btn btn-xs btn-default' %>
                <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                  <span class="caret"></span>
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to t('views.epp.links.edit'), edit_cost_path(cost) %></li>
                  <li><%= link_to t('views.epp.links.destroy'), cost, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to t('views.epp.links.new %{model}', :model => t("views.costs.cost")), new_cost_path, :class => 'btn btn-primary btn-lg hidden-print' %>
</div>

app/views/costs/new.html.erb
<%- title t("views.epp.links.new %{model}", :model => t("views.costs.costs")) %>
<div class="col-lg-12">
	<div class="page-header">
		<h1><%= t("views.epp.links.new %{model}", :model => t("views.costs.costs")) %></h1>
	</div>
	<%= render 'form' %>

</div>

app/views/costs/show.html.erb
<%- title "#{@cost.total_cost}" %>
<div class="col-lg-12 show">
	<div class="page-header">
		<h1><%= @cost.total_cost %></h1>
    <a title="Edit" href="<%= edit_activity_cost_path(@cost.activity) %>"><span class="glyphicon glyphicon-pencil"></span></a>
	</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.costs.total_cost") %></strong></div>


		<div class="col-sm-10"><%= @cost.total_cost ? number_with_precision(@cost.total_cost) :'N/A' %></div>
	</div>
   
    <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
              <th><%= t("views.lines.name") %></th>
              <th><%= t("views.lines.quantity") %></th>
              <th><%= t("views.lines.price") %></th>
              <th class="hidden-print"></th>
        </tr>
      </thead>

      <tbody>
        <% @cost.lines.each do |line| %>
          <tr>
    

            <td><%= line.name %></td>
    

            <td><%= line.quantity %></td>
    

            <td><%= line.price %></td>
                <td class="hidden-print actions">
              <div class="btn-group">
                <%= link_to t('views.epp.links.show'), line , :class => 'btn btn-xs btn-default' %>
                <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                  <span class="caret"></span>
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> 
</div>