config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :project_roles, :project_milestones, :professions, :project_attachments, :states,
            :states, :states, :activity_members, :organizations, :activities, :project_members,
            :project_donors, :project_partners, :projects, :members, :roles, :donors, :branches,
            :locations, :states, :users, :tags, :costs, :lines

  resource :trello_webhooks, only: %i(show create), defaults: { formats: :json }

  resources :projects do
    resources :project_attachments
  end

  # resources :projects do
  #   resources :project_members
  # end
  
  resources :activities do
    resource :cost
  end

  resource :project do
    post :add_member
    #get :remove_member
  end

  resource :activity do
    post :add_member
    #get :remove_member
  end
  
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1 , default: :true) do
      resources :projects
      resources :activities
    end
  end

  #get '/auth/twitter/callback', to: 'sessions#create'
  
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
    match "/confirm", to: "confirmations#confirm", via: :put 
    get '/auth/failure', to: 'sessions#new'
  end

  devise_for :users, :path => '', :path_names => { sign_in: 'login', sign_out: 'logout'}, :controllers => { omniauth_callbacks: "callbacks", confirmations: "confirmations", sessions: "sessions", registrations: "registrations" }

  get 'settings' => 'dashboard#settings', :as => "settings"

  root :to => "projects#index"
end

app/models/project.rb
require 'trello'

class Project < ActiveRecord::Base
  include Taggable

  enum currency: [ :USD, :SDG, :EUR ]

	belongs_to :branch
  has_many :project_milestones

  has_many :project_attachments

  belongs_to :location

  belongs_to :organization

  has_many :project_members
  has_many :members, through: :project_members
  
	has_many :project_donors
  has_many :donors, through: :project_donors


  has_many :project_roles
  has_many :roles, through: :project_roles

  has_many :project_partners
  has_many :organizations, through: :project_partners

	validates :name, uniqueness: true
	validates :name, :goal, :budget, presence: true
 	validates :budget, numericality: { allow_blank: true }

  accepts_nested_attributes_for :project_attachments
  accepts_nested_attributes_for :members  

  translates :name, :description, fallbacks_for_empty_translations: true
  accepts_nested_attributes_for :translations
  
  private
    def create_trello_board
      organization = Organization.first

      if organization.trello_member_token
        Trello.configure do |config|
          config.developer_public_key = ENV['TRELLO_KEY']
          config.member_token = organization.trello_member_token
        end

        board = Trello::Board.create(
          name: self.name,
          description: self.description
        )
        Trello::Webhook.create(description: "A webhook that update project model every time the card updated", id_model: board.id, callback_url: "https://blooming-woodland-20439.herokuapp.com/trello_webhooks")
        self.update(board: board.id)
      end
    end
end

app/controllers/api/v1/projects_controller.rb
require 'icalendar'
module Api
  module V1
    class ProjectsController < ApplicationController
      respond_to :json 
      
      def index
        respond_with Project.all
      end
      
      def show
        @project = Project.find(params[:id])
        render :show
     end
      
      def create
        respond_with Project.create(params[:project])
      end
      
      def update
        respond_with Project.update(params[:id], params[:projects])
      end
      
      def destroy
        respond_with Project.destroy(params[:id])
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.page(params[:page]).per(12)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
     @members = Member.where.not(id: @project.members.ids)   
    @activities = PublicActivity::Activity.all.order("created_at desc")
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.project_attachments.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
  
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def add_member
    ProjectMember.create({project_id: params[:project_id], member_id: params[:member_id]})
    redirect_to project_path(params[:project_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :budget, :from, :to, :branch_id, :location_id, :goal, :description, :tag_names, :currency, :created_by, :updated_by, project_attachments_attributes: [ :id, :file], translations_attributes: [:id, :locale, :name, :description], members_attributes: [:id,:name])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, html: { class: 'form-horizontal', multipart: true } do |f| %>
  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

    <div class="form-group">
      <%= f.label :name, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10"><%= f.text_field :name, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <%= f.label :budget, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10"><%= f.text_field :budget, :class => 'form-control' %></div>
    </div>
   

    <div class="form-group">
      <%= f.label :currency, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
      <%= f.select :currency, options_for_select(Project.currencies.collect { |s| [s[0], s[0]] }, selected: @project.currency), {} , class: "form-control"%></div>
    </div>


      <div class="form-group">
        <%= f.label :from, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group">
            <%= f.text_field :from, :class => 'form-control pickdate', :placeholder => 'YYYY-MM-DD' %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div>
        </div>
      </div>



      <div class="form-group">
        <%= f.label :to, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group">
            <%= f.text_field :to, :class => 'form-control pickdate', :placeholder => 'YYYY-MM-DD' %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div>
        </div>
      </div>

    <div class="form-group">
      <%= f.label :goal, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10"><%= f.text_area :goal, :class => 'form-control' %></div>
    </div>

    <div class="form-group">
      <%= f.label :description, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10"><%= f.text_area :description, :class => 'form-control' %></div>
    </div>
    
    <div class="form-group">
      <%= f.label :branch_id, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group">
            <%= f.select :branch_id, Branch.all.collect {|p| [ p.name, p.id ] }, {}, { :class => 'form-control' } %>
            <span class="input-group-btn">
            <%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_branch_path, :class => 'btn btn-default', :target => '_blank' %>
            <%= link_to raw('<span class="glyphicon glyphicon-play"></span>'), branches_path, :class => 'btn btn-default goto' %>
            </span>
          </div>
      </div>
    </div>  

        <div class="form-group">
        <%= f.label :location_id, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group">
            <%= f.select :location_id, Location.all.collect {|p| [ p.name, p.id ] }, {}, { :class => 'form-control' } %>
            <span class="input-group-btn">
            <%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_location_path, :class => 'btn btn-default', :target => '_blank' %>
            <%= link_to raw('<span class="glyphicon glyphicon-play"></span>'), locations_path, :class => 'btn btn-default goto' %>
            </span>
          </div>
        </div>
      </div>


 <div class="form-group">
      <% if Project.exists?(@project.id) && @project.project_attachments.any? %>
          <div class="col-sm-2 control-label"><strong><%= t("views.projects.attachments") %></strong></div>
          <div class="col-sm-10">
            <ul>
              <% @project.project_attachments.each do |project_attachment| %>
                <li> <%= project_attachment.file_file_name %>
                <%= link_to raw("<i class='fa fa-times'></i> " + t("views.project.Remove")), [@project, project_attachment], method: :delete %>
                </li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>

    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= link_to_add_fields t("views.projects.add_attachment") , f, :project_attachments %>
      </div> 
    </div>

      <div class="page-header">
        <div class="row">
          <h4><%= t("views.epp.links.translation fields") %></h4>
        </div>  
      </div>
    <%= f.globalize_fields_for other_locale do |ff| %>
      <%= ff.hidden_field :locale, value: other_locale %>
      <div class="form-group">
        <%= ff.label t("views.donors.name")+t("views.epp.links.in %{lang}", lang: t("views.epp.links.#{other_locale.to_s}")), :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= ff.text_field :name, :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= ff.label t("views.donors.description")+t("views.epp.links.in %{lang}", lang: t("views.epp.links.#{other_locale.to_s}")), :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= ff.text_area :description, :class => 'form-control' %>
        </div>
      </div>
    <% end %>
        
  <div class="buttons">
    <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-floppy-disk"></span><%= t('views.epp.links.save') %></button>
    <%= link_to raw("<span class='glyphicon glyphicon-trash'></span> #{t('views.epp.links.back')}"), projects_path , :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/projects/_project_attachment_form.html.erb
<div class="form-group">
  <%= f.label :file, :class => 'col-sm-2 control-label' %>
  <div class="col-sm-10"><%= f.file_field :file, :class => 'form-control' %>
  </div>
</div>

app/views/projects/edit.html.erb
<%- title t("views.epp.links.edit %{model}", :model => t("views.projects.project")) %>

<div class="col-lg-12">
	<div class="page-header">
		<h1><%= t("views.epp.links.edit %{model}", :model => t("views.projects.project")) %></h1>
	</div>
	<%= render 'form' %>

</div>

app/views/projects/index.html.erb
<%- title t "views.application_layout.projects" %>
<div class="col-xs-12">

  <div class="page-header">
    <h1><%= t "views.application_layout.projects" %>
      <%= link_to link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_project_path , :class => 'btn btn-lg hidden-print' %>
    </h1>
  </div>


  <div class="tags-cloud" data-source='<%= Tag.all.collect(&:name).to_json %>'>
    <ul class="tags">
      <% Project.tags.each do |tag| %>
        <li><a href="#" class="tag-link tag-<%= tag.id %>" data-path="<%= tag_path(tag) %>" data-color="<%= tag.color_code %>"><%= tag.name %></a></li>
      <% end %>
    </ul>

    <style>
      <% Tag.all.each do |tag| %>
        a.tag-link.tag-<%= tag.id %> {background: <%= tag.color_code %>;}
        a.tag-link.tag-<%= tag.id %>:before {border-color:transparent <%= tag.color_code %> transparent transparent;}
      <% end %>
    </style>
  </div>
</div>  
 

<% @projects.each do |project| %>
  <div class="entity-box col-md-3 col-sm-6 col-xs-12">
    <div class="info-box"  style="background-color: #1BB099">
      <ul class="action-menu">
        <li><a title="show" href="<%= project_path(project) %>"><span class="glyphicon glyphicon-file"></span></a></li>
        <li><a title="Edit" href="<%= edit_project_path(project) %>"><span class="glyphicon glyphicon-pencil"></span></a></li>  
        <li><a title="edit_tags" class="edit-tags" href="#" data-tags="<%= project.tag_names %>" data-path="<%= project_path(project) %>" data-model="project" ><span class="glyphicon glyphicon-tag"></span></a></li> 
      </ul>

  <div class="info-box-content">
        <a href="<%= project_path(project) %>">
        <span class="info-box-text"><%= project.name %></span>
        
        <span class="progress-description"> 
            <p><%= project.budget %></p>


            <p><%= project.goal %></p>
        </span>
        </a>
        <%= render :partial => "layouts/entity_tags", :locals => {tags: project.tags } if project.tags.count > 0 %>
      </div>
    </div>
  </div>
<% end %>
<div class="paginator"><%= paginate @projects %></div>

app/views/projects/new.html.erb
<%- title t("views.epp.links.new %{model}", :model => t("views.projects.projects")) %>
<div class="col-lg-12">
	<div class="page-header">
		<h1><%= t("views.epp.links.new %{model}", :model => t("views.projects.projects")) %></h1>
	</div>
	<%= render 'form' %>

</div>

app/views/projects/show.html.erb
<%- title "#{@project.name}" %>
<div class="col-lg-12 show">
	<div class="page-header">
		<h1><%= @project.name %></h1>
		<a title="Edit" href="<%= edit_project_path(@project) %>"><span class="glyphicon glyphicon-pencil"></span></a>
	</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.projects.name") %></strong></div>


		<div class="col-sm-10"><%= @project.try(:name) || 'N/A' %></div>
	</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.projects.budget") %></strong></div>


		<div class="col-sm-10"><%= @project.try(:budget) || 'N/A' %></div>
	</div>
  
  <div class="row">
  	<div class="col-sm-2"><strong><%= t("views.projects.currency") %></strong></div>


  	<div class="col-sm-10"><%= @project.try(:currency) || 'N/A' %></div>
  </div>
  
	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.projects.from") %></strong></div>


		<div class="col-sm-10"><%= @project.try(:from) || 'N/A' %></div>
	</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.projects.to") %></strong></div>


		<div class="col-sm-10"><%= @project.try(:to) || 'N/A' %></div>
	</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.projects.goal") %></strong></div>


		<div class="col-sm-10"><%= @project.try(:goal) || 'N/A' %></div>
	</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.projects.description") %></strong></div>


		<div class="col-sm-10"><%= @project.try(:description) || 'N/A' %></div>
	</div>
   
  <div class="row">
		<div class="col-sm-2"><strong><%= t("views.projects.location_id") %></strong></div>
		<div class="col-sm-10"><%= link_to @project.location.name, @project.location if @project.location_id %></div>
		</div>
    
     	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.projects.branch_id") %></strong></div>
    	<div class="col-sm-10"><%= link_to @project.branch.name, @project.branch if @project.branch_id %></div>
		</div>

	  <div class="row">
	  	<div class="col-sm-2"><strong><%= t("views.projects.attachments") %></strong></div>
	    <div class="col-sm-10">
	    	<% if @project.project_attachments.any? %>
			  	<ul>
				  	<% @project.project_attachments.each do |project_attachment| %>
							<li><%= link_to project_attachment.file_file_name, project_attachment_path(project_attachment) %></li>
				    <% end %>
				  </ul>
				<% else %>
					<p>NA</p>
				<% end %>
	    <div>
		</div>
  </div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.projects.members") %></strong></div>
    <div class="col-sm-10">
		<ul class="quite">
			<% @project.project_members.each do |project_member|  %>
				<li>
					<%= link_to project_member.member.name, member_path(project_member.member.id)%>	
					<%= link_to raw("<i class='fa fa-times'></i> " + t("views.projects.Remove")), project_member_path(project_member.id), method: :delete, data: { confirm: 'Are you sure?' } %>
				</li>
			<% end %>
		</ul>		
		<% if @members.size > 0 %>
			<%= form_tag({controller: "projects" , action: "add_member" , method: "post"}, {class:"form-inline"}) do %>
				<%= select_tag(:member_id,options_for_select(@members.collect{|member| [member.name, member.id]}), class: "select2 form-control") %>
				<%= hidden_field_tag(:project_id, @project.id) %>
				<%= submit_tag t('views.projects.Add Member'), class: 'btn btn-default'%>
			<% end %>
		<% end %>
    </div>
  </div>
</div>