config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  resources :project_roles, :project_milestones, :professions, :project_attachments, :states,
            :states, :states, :activity_members, :organizations, :activities, :project_members,
            :project_donors, :project_partners, :projects, :members, :roles, :donors, :branches,
            :locations, :states, :users, :tags, :costs, :lines

  resource :trello_webhooks, only: %i(show create), defaults: { formats: :json }

  resources :projects do
    resources :project_attachments
  end

  # resources :projects do
  #   resources :project_members
  # end
  
  resources :activities do
    resource :cost
  end

  resource :project do
    post :add_member
    #get :remove_member
  end

  resource :activity do
    post :add_member
    #get :remove_member
  end
  
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1 , default: :true) do
      resources :projects
      resources :activities
    end
  end

  #get '/auth/twitter/callback', to: 'sessions#create'
  
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
    match "/confirm", to: "confirmations#confirm", via: :put 
    get '/auth/failure', to: 'sessions#new'
  end

  devise_for :users, :path => '', :path_names => { sign_in: 'login', sign_out: 'logout'}, :controllers => { omniauth_callbacks: "callbacks", confirmations: "confirmations", sessions: "sessions", registrations: "registrations" }

  get 'settings' => 'dashboard#settings', :as => "settings"

  root :to => "projects#index"
end

app/models/project_member.rb
class ProjectMember < ActiveRecord::Base
  include StampableRelations
  
	belongs_to :member
	belongs_to :project
  belongs_to :role
  
end

app/controllers/project_members_controller.rb
class ProjectMembersController < ApplicationController
  load_and_authorize_resource
  before_action :set_project_member, only: [:show, :edit, :update, :destroy]

  # GET /project_members
  # GET /project_members.json
  def index
    @project_members = ProjectMember.all
  end

  # GET /project_members/1
  # GET /project_members/1.json
  def show
  end

  # GET /project_members/new
  def new
    @project_member = ProjectMember.new
  end

  # GET /project_members/1/edit
  def edit
  end

  # POST /project_members
  # POST /project_members.json
  def create
    @project_member = ProjectMember.new(project_member_params)

    respond_to do |format|
      if @project_member.save
        format.html { redirect_to @project_member, notice: 'Project member was successfully created.' }
        format.json { render :show, status: :created, location: @project_member }
      else
        format.html { render :new }
        format.json { render json: @project_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_members/1
  # PATCH/PUT /project_members/1.json
  def update
    respond_to do |format|
      if @project_member.update(project_member_params)
        format.html { redirect_to @project_member, notice: 'Project member was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_member }
      else
        format.html { render :edit }
        format.json { render json: @project_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_members/1
  # DELETE /project_members/1.json
  def destroy
    @project = @project_member.project
    @project_member.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Project member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_member
      @project_member = ProjectMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_member_params
      params.require(:project_member).permit(:project_id, :member_id, :created_by, :updated_by)
    end
end

app/helpers/project_members_helper.rb
module ProjectMembersHelper
end

app/views/project_members/_form.html.erb
<%= form_for @project_member, :html => {:class => 'form-horizontal'} do |f| %>
  <% if @project_member.errors.any? %>
    <% @project_member.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  

      <div class="form-group">
        <%= f.label :project_id, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group">
            <%= f.select :project_id, Project.all.collect {|p| [ p.name, p.id ] }, {}, { :class => 'form-control' } %>
            <span class="input-group-btn">
            <%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_project_path, :class => 'btn btn-default', :target => '_blank' %>
            <%= link_to raw('<span class="glyphicon glyphicon-play"></span>'), projects_path, :class => 'btn btn-default goto' %>
            </span>
          </div>
        </div>
      </div>


      <div class="form-group">
        <%= f.label :member_id, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group">
            <%= f.select :member_id, Member.all.collect {|p| [ p.name, p.id ] }, {}, { :class => 'form-control' } %>
            <span class="input-group-btn">
            <%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_member_path, :class => 'btn btn-default', :target => '_blank' %>
            <%= link_to raw('<span class="glyphicon glyphicon-play"></span>'), members_path, :class => 'btn btn-default goto' %>
            </span>
          </div>
        </div>
      </div>

  
  <div class="form-group">
    <label class="col-sm-2 control-label" for="attachment_file"></label>
    <div class="col-sm-10"><button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-floppy-disk"></span> <%= t('views.epp.links.save') %></button></div>
  </div>
      
<% end %>

app/views/project_members/edit.html.erb
<%- title t("views.epp.links.edit %{model}", :model => t("views.project_members.project_members")) %>

<div class="col-lg-12">
	<div class="page-header">
		<h1><%= t("views.epp.links.edit %{model}", :model => t("views.project_members.project_members")) %></h1>
	</div>
	<%= render 'form' %>

</div>

app/views/project_members/index.html.erb
<%- title t "views.application_layout.project_members" %>
<div class="col-xs-12">

  <div class="page-header">
    <h1><%= t "views.application_layout.project_members" %> <small><%= t("views.epp.Listing of all %{model}", :model => t("views.project_members.project_members")) %></small></h1>
  </div>


  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
              <th><%= t("views.project_members.project_id") %></th>
              <th><%= t("views.project_members.member_id") %></th>
              <th class="hidden-print"></th>
        </tr>
      </thead>

      <tbody>
        <% @project_members.each do |project_member| %>
          <tr>
    
            <td><%= link_to project_member.project.name, project_member.project if project_member.project_id %></td>

            <td><%= link_to project_member.member.name, project_member.member if project_member.member_id %></td>

            <td class="hidden-print actions">
              <div class="btn-group">
                <%= link_to t('views.epp.links.show'), project_member , :class => 'btn btn-xs btn-default' %>
                <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                  <span class="caret"></span>
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to t('views.epp.links.edit'), edit_project_member_path(project_member) %></li>
                  <li><%= link_to t('views.epp.links.destroy'), project_member, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to t('views.epp.links.new %{model}', :model => t("views.project_members.project_member")), new_project_member_path, :class => 'btn btn-primary btn-lg hidden-print' %>
</div>

app/views/project_members/new.html.erb
<%- title t("views.epp.links.new %{model}", :model => t("views.project_members.project_members")) %>
<div class="col-lg-12">
	<div class="page-header">
		<h1><%= t("views.epp.links.new %{model}", :model => t("views.project_members.project_members")) %></h1>
	</div>
	<%= render 'form' %>

</div>

app/views/project_members/show.html.erb
<%- title "#{@project_member.project_id}" %>
<div class="col-lg-12 show">
	<div class="page-header">
		<h1><%= @project_member.project_id %></h1>
	</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.project_members.project_id") %></strong></div>

		<div class="col-sm-10"><%= link_to @project_member.project.name, @project_member.project if @project_member.project_id %></div>
		</div>

	<div class="row">
		<div class="col-sm-2"><strong><%= t("views.project_members.member_id") %></strong></div>

		<div class="col-sm-10"><%= link_to @project_member.member.name, @project_member.member if @project_member.member_id %></div>
		</div>

	<div class="buttons">
		<%= link_to t('views.epp.links.edit'), edit_project_member_path(@project_member), :class => 'btn btn-warning' %>
		<%= link_to t('views.epp.links.back'), project_members_path, :class => 'btn btn-default' %>
	</div>
</div>